apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: yo-go-tkn 
  janus-idp.io/tekton: yo-go-tkn
  backstage.io/kubernetes-id: yo-go-tkn
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yo-go-tkn
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  